using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Shirubasoft.Aspire.E2E.Hosting.Generator;

[Generator]
public class SharedResourceGenerator : IIncrementalGenerator
{
    private const string JsonFileName = "SharedResourceReferences.g.json";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resourceFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(JsonFileName))
            .Select(static (file, ct) => file.GetText(ct)?.ToString());

        context.RegisterSourceOutput(resourceFiles, static (spc, jsonText) =>
        {
            if (string.IsNullOrWhiteSpace(jsonText))
                return;

            var resources = ParseResources(jsonText);

            foreach (var resource in resources)
            {
                GenerateResourceCode(spc, resource);
            }
        });
    }

    private static ImmutableArray<ResourceDefinition> ParseResources(string json)
    {
        // Minimal JSON parsing without System.Text.Json (not available in netstandard2.0 analyzer context)
        var builder = ImmutableArray.CreateBuilder<ResourceDefinition>();
        var entries = json.Split(new[] { '{' }, System.StringSplitOptions.RemoveEmptyEntries);

        foreach (var entry in entries)
        {
            if (!entry.Contains("\"Id\""))
                continue;

            var id = ExtractJsonValue(entry, "Id");
            var name = ExtractJsonValue(entry, "Name");
            var mode = ExtractJsonValue(entry, "Mode");
            var projectPath = ExtractJsonValue(entry, "ProjectPath");

            if (string.IsNullOrEmpty(id))
                continue;

            // Default name to PascalCase of id if not provided
            if (string.IsNullOrEmpty(name))
                name = ToPascalCase(id);

            builder.Add(new ResourceDefinition(id, name, mode, projectPath));
        }

        return builder.ToImmutable();
    }

    private static string ExtractJsonValue(string json, string key)
    {
        var searchKey = "\"" + key + "\": \"";
        var startIndex = json.IndexOf(searchKey);
        if (startIndex < 0)
            return string.Empty;

        startIndex += searchKey.Length;
        var endIndex = json.IndexOf("\"", startIndex);
        if (endIndex < 0)
            return string.Empty;

        return json.Substring(startIndex, endIndex - startIndex);
    }

    private static string ToPascalCase(string input)
    {
        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in input)
        {
            if (c == '-' || c == '_' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }

            sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
            capitalizeNext = false;
        }

        return sb.ToString();
    }

    private static void GenerateResourceCode(SourceProductionContext context, ResourceDefinition resource)
    {
        var isProjectMode = string.Equals(resource.Mode, "Project", System.StringComparison.OrdinalIgnoreCase)
            && !string.IsNullOrEmpty(resource.ProjectPath);

        var projectBranch = isProjectMode
            ? $@"            resourceBuilder = builder.AddProject<{resource.Name}ProjectMetadata>(""{resource.Id}"");"
            : $@"            resourceBuilder = builder.AddProject(
                ""{resource.Id}"",
                builder.Configuration.GetValue<string>(""Aspire:Resources:{resource.Id}:ProjectPath"")!);";

        var metadataClass = isProjectMode
            ? $@"

[global::System.CodeDom.Compiler.GeneratedCode(""Shirubasoft.Aspire.E2E.Hosting.Generator"", null)]
public class {resource.Name}ProjectMetadata : global::Aspire.Hosting.IProjectMetadata
{{
    public string ProjectPath => @""{resource.ProjectPath}"";
}}"
            : "";

        var source = $@"// <auto-generated />
using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;
using Microsoft.Extensions.Configuration;
using Shirubasoft.Aspire.E2E.Hosting;

namespace Shirubasoft.Aspire.E2E.Hosting.Generated;

public interface I{resource.Name}ResourceBuilder
{{
    {resource.Name}ResourceBuilder ConfigureContainer(System.Action<IResourceBuilder<ContainerResource>> configure);
    {resource.Name}ResourceBuilder ConfigureProject(System.Action<IResourceBuilder<ProjectResource>> configure);
    {resource.Name}ResourceBuilder Configure<T>(System.Action<IResourceBuilder<T>> configure) where T : IResource;
}}

public sealed class {resource.Name}ResourceBuilder(IResourceBuilder<IResource> resourceBuilder) : ResourceBuilderProxy(resourceBuilder), I{resource.Name}ResourceBuilder
{{
    public new {resource.Name}ResourceBuilder ConfigureContainer(System.Action<IResourceBuilder<ContainerResource>> configure)
    {{
        base.ConfigureContainer(configure);
        return this;
    }}

    public new {resource.Name}ResourceBuilder ConfigureProject(System.Action<IResourceBuilder<ProjectResource>> configure)
    {{
        base.ConfigureProject(configure);
        return this;
    }}

    public new {resource.Name}ResourceBuilder Configure<T>(System.Action<IResourceBuilder<T>> configure) where T : IResource
    {{
        base.Configure(configure);
        return this;
    }}
}}

public static class {resource.Name}ResourceExtensions
{{
    public static I{resource.Name}ResourceBuilder Add{resource.Name}(this IDistributedApplicationBuilder builder)
    {{
        IResourceBuilder<IResource> resourceBuilder;

        if (builder.Configuration.GetValue<ResourceMode>(""Aspire:Resources:{resource.Id}:Mode"") == ResourceMode.Container)
        {{
            resourceBuilder = builder.AddContainer(
                ""{resource.Id}"",
                builder.Configuration.GetValue<string>(""Aspire:Resources:{resource.Id}:ContainerImage"")!,
                builder.Configuration.GetValue<string>(""Aspire:Resources:{resource.Id}:ContainerTag"")!);
        }}
        else
        {{
{projectBranch}
        }}

        return new {resource.Name}ResourceBuilder(resourceBuilder);
    }}
}}{metadataClass}
";
        context.AddSource($"{resource.Name}Resource.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string DeriveProjectsTypeName(string projectPath)
    {
        // Extract filename without extension, then replace . and - with _
        var fileName = projectPath;
        var lastSlash = fileName.LastIndexOf('/');
        var lastBackslash = fileName.LastIndexOf('\\');
        var lastSep = System.Math.Max(lastSlash, lastBackslash);
        if (lastSep >= 0)
            fileName = fileName.Substring(lastSep + 1);

        // Remove .csproj extension
        if (fileName.EndsWith(".csproj"))
            fileName = fileName.Substring(0, fileName.Length - 7);

        // Replace . and - with _
        return fileName.Replace('.', '_').Replace('-', '_');
    }

    private sealed class ResourceDefinition
    {
        public string Id { get; }
        public string Name { get; }
        public string Mode { get; }
        public string ProjectPath { get; }

        public ResourceDefinition(string id, string name, string mode, string projectPath)
        {
            Id = id;
            Name = name;
            Mode = mode;
            ProjectPath = projectPath;
        }
    }
}
